### ISSUE TITLE
Make sure `kd` is installed

### ISSUE THREAD

**Issue by usirin** [koding/node-kd#1]
For `kdx` (therefore `node-kd`) to work, `kd` should be installed in the system.

/cc @rjeczalik

**Comment by usirin** [comment]
@rjeczalik what would be the best way to install (preferably the bleeding edge version) of `kd`?

**Comment by rjeczalik** [comment]
```
brew tap rjeczalik/kd
brew install kd --devel
```

After I'm done with https://github.com/koding/koding/pull/10394 then the repo would become `koding/kd`.
